name: tests

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
    branches-ignore:
      - 'gh-pages'

jobs:
  ci:
    strategy:
      matrix:
        go: ['1.17', '1.18', '1.19', '1.20', '1.21', '1.22']
        platform: [ubuntu-latest, macos-latest] # can not run in windows OS
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        cache: false

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Tests
      run: go test
